title: "aezi's blog"
description: "Welcome to all my thoughts and views. Enjoy."
url: "https://blog.aezlo.com"
#baseurl:

header_pages:
  - socials.md
  - peter.md
  - about.md
  - contact.md

footer: 'follow me on <a href="https://twitter.com/aezlox">twitter</a> or email me <a href="mailto:pixelfest0@gmail.com">here</a>'

style: dark
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
